-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/EntitySchema/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/entityschema_id_counter (id_value INTEGER UNSIGNED NOT NULL);
